  name: swipify
  description: "A new Flutter project."
  publish_to: 'none'
  version: 0.1.0

  environment:
    sdk: ^3.9.0

  dependencies:
    audioplayers: ^6.5.1
    flutter:
      sdk: flutter
    flutter_appauth: ^11.0.0
    flutter_card_swiper: ^7.2.0
    flutter_dotenv: ^6.0.0
    flutter_secure_storage: ^9.2.4
    get: ^4.7.3
    http: ^1.6.0
    provider: ^6.1.5+1
    test: ^1.26.2
    url_launcher: ^6.3.2
    integration_test:
      sdk: flutter
    

  dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: ^5.0.0

  flutter:
    assets:
      - assets/
      - assets/images/
    uses-material-design: true
